### ISSUE TITLE
Warning with Powerpoint template

### ISSUE THREAD

**Issue by Edouard-Legoupil** [vidonne/unhcrdown#29]
Got the following warning with  unhcrdown::pptx_slides

[WARNING] Powerpoint template warning: Couldn't find layout named "Comparison" in provided reference doc. Falling back to the default included with pandoc.
[WARNING] Powerpoint template warning: Couldn't find layout named "Content with Caption" in provided reference doc. Falling back to the default included with pandoc.
[WARNING] Powerpoint template warning: Couldn't find layout named "Blank" in provided reference doc. Falling back to the default included with pandoc.

**Comment by vidonne** [comment]
Hi Edouard,
I couldn't replicate the error and checked the [ppt_template](https://github.com/vidonne/unhcrdown/blob/master/inst/resources/templates/pptx_template.pptx) file it includes all the mentioned layout name of the warnings.
Maybe try to force the installation of the package and could you provide more details if the error still appears.

**Comment by Edouard-Legoupil** [comment]
ok -- not sure why but did not get this again - closing for the moment
